[[main]]
  identifier = "content"
  name = "Content"
  weight = 10

[[main]]
  parent = "content"
  identifier = "wiki"
  name = "Wiki"
  pageRef = "/wiki/"
  weight = 11

[[main]]
  parent = "content"
  identifier = "tutorials"
  name = "Tutorials"
  pageRef = "/tutorials/"
  weight = 12

[[main]]
  parent = "content"
  identifier = "posts"
  name = "Posts"
  pageRef = "/posts/"
  weight = 13

[[main]]
  identifier = "tags"
  name = "Tags"
  pageRef = "/tags/"
  weight = 20

[[main]]
  identifier = "about"
  name = "About"
  pageRef = "/about/"
  weight = 30
