[[main]]
  identifier = "journal"
  name = "Journal"
  pageRef = "/journal/"
  weight = 10

[[main]]
  identifier = "content"
  name = "Content"
  weight = 20

[[main]]
  parent = "content"
  identifier = "wiki"
  name = "Wiki"
  pageRef = "/wiki/"
  weight = 21

[[main]]
  parent = "content"
  identifier = "tutorials"
  name = "Tutorials"
  pageRef = "/tutorials/"
  weight = 22

[[main]]
  parent = "content"
  identifier = "posts"
  name = "Posts"
  pageRef = "/posts/"
  weight = 23

[[main]]
  parent = "content"
  identifier = "series"
  name = "Series"
  pageRef = "/series/"
  weight = 24

[[main]]
  identifier = "tags"
  name = "Tags"
  pageRef = "/tags/"
  weight = 30

[[main]]
  identifier = "about"
  name = "About"
  pageRef = "/about/"
  weight = 40
